// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/ping/protobuf/ping.proto

package go_micro_service_ping

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protobuf "github.com/reversTeam/go-ms/services/goms/protobuf"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("services/ping/protobuf/ping.proto", fileDescriptor_8a2538da1e0a4962) }

var fileDescriptor_8a2538da1e0a4962 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4a, 0x3b, 0x31,
	0x10, 0xc6, 0xf9, 0xff, 0x5b, 0x57, 0x08, 0x8a, 0x12, 0xa8, 0x87, 0xea, 0xc5, 0x7a, 0x91, 0x82,
	0x09, 0xd4, 0x9b, 0xe0, 0x49, 0x4b, 0x2f, 0x0a, 0xb2, 0x28, 0x9e, 0x77, 0xb7, 0x63, 0x1a, 0x6c,
	0x32, 0x31, 0x99, 0x2d, 0x14, 0xf1, 0xe2, 0x2b, 0xf8, 0x68, 0xbe, 0x82, 0x4f, 0xe1, 0x49, 0x36,
	0xbb, 0xd6, 0x82, 0x20, 0x82, 0x3d, 0x0e, 0xdf, 0x7c, 0xdf, 0x6f, 0x3e, 0x86, 0xed, 0x07, 0xf0,
	0x33, 0x5d, 0x40, 0x90, 0x4e, 0x5b, 0x25, 0x9d, 0x47, 0xc2, 0xbc, 0xbc, 0x8b, 0x93, 0x88, 0x13,
	0xef, 0x28, 0x14, 0x46, 0x17, 0x1e, 0x45, 0xb3, 0x2b, 0x2a, 0xb1, 0xbb, 0xa7, 0x10, 0xd5, 0x14,
	0x64, 0xe6, 0xb4, 0xcc, 0xac, 0x45, 0xca, 0x48, 0xa3, 0x0d, 0xb5, 0xa9, 0xbb, 0xdb, 0xa8, 0x8b,
	0x40, 0x30, 0x8e, 0xe6, 0x8d, 0x78, 0xaa, 0x34, 0x4d, 0xca, 0x5c, 0x14, 0x68, 0xa4, 0x87, 0x19,
	0xf8, 0x70, 0x0d, 0x99, 0x91, 0x0a, 0x8f, 0x4c, 0x90, 0x8b, 0x83, 0x14, 0x9a, 0xf0, 0xe5, 0xaf,
	0xa6, 0xda, 0x3e, 0x78, 0x6f, 0xb1, 0xf6, 0x95, 0xb6, 0x8a, 0xa7, 0xac, 0x7d, 0xa1, 0x03, 0xf1,
	0x1d, 0x51, 0xd3, 0xc4, 0xe7, 0xb6, 0x18, 0x56, 0xb4, 0xee, 0x81, 0xf8, 0x76, 0x7a, 0x8c, 0x19,
	0xe1, 0x65, 0x48, 0x21, 0x38, 0xb4, 0x01, 0x7a, 0x9b, 0xcf, 0xaf, 0x6f, 0x2f, 0xff, 0xd7, 0xf9,
	0x5a, 0xec, 0xcc, 0x6f, 0x59, 0x72, 0xe6, 0x21, 0x23, 0xf8, 0x5b, 0xea, 0x76, 0x4c, 0x65, 0xbd,
	0x3a, 0xf5, 0xe4, 0x5f, 0x9f, 0x4f, 0x58, 0x6b, 0x04, 0xc4, 0x0f, 0x7f, 0x70, 0x0f, 0x2d, 0x69,
	0x9a, 0xa7, 0xf0, 0x50, 0x42, 0xa0, 0xdf, 0x71, 0x78, 0xe4, 0x6c, 0x70, 0x56, 0xff, 0xef, 0x51,
	0x8f, 0x9f, 0xb8, 0x65, 0xc9, 0x8d, 0x1b, 0x57, 0x15, 0x56, 0x0c, 0xeb, 0x44, 0xd8, 0xd6, 0x60,
	0x09, 0x56, 0x35, 0xbb, 0x67, 0xc9, 0x39, 0x4c, 0x61, 0xf5, 0xbc, 0xa6, 0x5c, 0x7f, 0x89, 0x97,
	0x27, 0xf1, 0x1b, 0xc7, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x66, 0x35, 0x0c, 0xb9, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingClient is the client API for Ping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingClient interface {
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error)
	Create(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error)
	Get(ctx context.Context, in *protobuf.GoMsEntityRequest, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error)
	Update(ctx context.Context, in *protobuf.GoMsEntityRequest, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error)
	Delete(ctx context.Context, in *protobuf.GoMsEntityRequest, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error) {
	out := new(protobuf.GoMsResponse)
	err := c.cc.Invoke(ctx, "/go.micro.service.ping.Ping/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) Create(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error) {
	out := new(protobuf.GoMsResponse)
	err := c.cc.Invoke(ctx, "/go.micro.service.ping.Ping/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) Get(ctx context.Context, in *protobuf.GoMsEntityRequest, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error) {
	out := new(protobuf.GoMsResponse)
	err := c.cc.Invoke(ctx, "/go.micro.service.ping.Ping/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) Update(ctx context.Context, in *protobuf.GoMsEntityRequest, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error) {
	out := new(protobuf.GoMsResponse)
	err := c.cc.Invoke(ctx, "/go.micro.service.ping.Ping/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) Delete(ctx context.Context, in *protobuf.GoMsEntityRequest, opts ...grpc.CallOption) (*protobuf.GoMsResponse, error) {
	out := new(protobuf.GoMsResponse)
	err := c.cc.Invoke(ctx, "/go.micro.service.ping.Ping/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServer is the server API for Ping service.
type PingServer interface {
	List(context.Context, *empty.Empty) (*protobuf.GoMsResponse, error)
	Create(context.Context, *empty.Empty) (*protobuf.GoMsResponse, error)
	Get(context.Context, *protobuf.GoMsEntityRequest) (*protobuf.GoMsResponse, error)
	Update(context.Context, *protobuf.GoMsEntityRequest) (*protobuf.GoMsResponse, error)
	Delete(context.Context, *protobuf.GoMsEntityRequest) (*protobuf.GoMsResponse, error)
}

// UnimplementedPingServer can be embedded to have forward compatible implementations.
type UnimplementedPingServer struct {
}

func (*UnimplementedPingServer) List(ctx context.Context, req *empty.Empty) (*protobuf.GoMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedPingServer) Create(ctx context.Context, req *empty.Empty) (*protobuf.GoMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedPingServer) Get(ctx context.Context, req *protobuf.GoMsEntityRequest) (*protobuf.GoMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedPingServer) Update(ctx context.Context, req *protobuf.GoMsEntityRequest) (*protobuf.GoMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedPingServer) Delete(ctx context.Context, req *protobuf.GoMsEntityRequest) (*protobuf.GoMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.service.ping.Ping/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.service.ping.Ping/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Create(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protobuf.GoMsEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.service.ping.Ping/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Get(ctx, req.(*protobuf.GoMsEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protobuf.GoMsEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.service.ping.Ping/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Update(ctx, req.(*protobuf.GoMsEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protobuf.GoMsEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.service.ping.Ping/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Delete(ctx, req.(*protobuf.GoMsEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.service.ping.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Ping_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Ping_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Ping_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Ping_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Ping_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/ping/protobuf/ping.proto",
}
