grpc:
  host: "127.0.0.1"
  port: 42001
http:
  host: "127.0.0.1"
  port: 8080
exporter:
  host: "127.0.0.1"
  port: 4242
  path: "/metrics"
  interval: 1
services:
  abs:
    http: true
    config:
      database:
        host: 127.0.0.1
        port: 3306
  child:
    http: true
    config:
      database:
        host: 127.0.0.1
        port: 5432
  ping:
    http: true
    config:
      database:
        host: 127.0.0.1
        port: 5432
jaeger:
  name: skeleton
  unsecure: true
  mode: http
  host: 127.0.0.1
  port: 4318
  sampler:
    type: "const"
    param: 1
  reporter:
    logSpans: true