name: skeleton
grpc:
  host: "127.0.0.1"
  port: 42001
http:
  host: "0.0.0.0"
  port: 8080
exporter:
  host: "127.0.0.1"
  port: 4242
  path: "/metrics"
  interval: 1
middlewares:
  - TestMiddleware
services:
  abs:
    http: true
    config:
      database:
        host: 127.0.0.1
        port: 3306
  child:
    http: true
    config:
      database:
        host: 127.0.0.1
        port: 5432
  ping:
    http: true
    config:
      database:
        host: 127.0.0.1
        port: 5432
      middlewares:
        List:
          - AuthMiddleware
          - TestMiddleware
        Create:
          - ValidationMiddleware
          - RateLimitMiddleware
          - AuthMiddleware
        Get:
          - AuthMiddleware
        Update:
          - ValidationMiddleware
          - AuthMiddleware
        Delete:
          - AuthMiddleware

jaeger:
  unsecure: true
  mode: http
  host: 127.0.0.1
  port: 4318
  sampler:
    type: "const"
    param: 1
  reporter:
    logSpans: true