name: skeleton
grpc:
  host: 127.0.0.1
  port: 42001
http:
  host: 0.0.0.0
  port: 8080
exporter:
  host: 127.0.0.1
  port: 4242
  path: "/metrics"
  interval: 1
services:
  signin:
    http: true
    config:
      databases:
        scylla:
          global:
            host: 127.0.0.1
            port: 9042
          auth:
            host: 127.0.0.1
            port: 9042
      middlewares:
        Register:
          - UnAuthMiddleware
        Validate:
          - UnAuthMiddleware
  people:
    http: true
    config:
      databases:
        scylla:
          global:
            host: 127.0.0.1
            port: 9042
      middlewares:
        List:
          - AuthMiddleware
        Get:
          - AuthMiddleware
  account:
    http: false
    config:
      databases:
        scylla:
          global:
            host: 127.0.0.1
            port: 9042
          auth:
            host: 127.0.0.1
            port: 9042
  email:
    http: false
    config:
      databases:
        scylla:
          global:
            host: 127.0.0.1
            port: 9042
          auth:
            host: 127.0.0.1
            port: 9042

jaeger:
  unsecure: true
  mode: http
  host: 127.0.0.1
  port: 4318
  sampler:
    type: "const"
    param: 1
  reporter:
    logSpans: true